/**
 * ReviewGround - GitHub Checks & PR Description Automation
 * Handles PR description updates with AI summaries and GitHub Check Run gate creation.
 */

/**
 * Auto-updates the PR body with an AI-generated summary, changed-areas
 * checklist, and a risk level badge.
 */
export async function updatePrDescription(
  reviewText: string,
  token: string,
  repo: string,
  prNumber: string
): Promise<void> {
  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'User-Agent': 'ReviewGround-CI-Reviewer',
    'Content-Type': 'application/json',
  };

  try {
    const prRes = await fetch(`https://api.github.com/repos/${repo}/pulls/${prNumber}`, { headers });
    if (!prRes.ok) {
      console.warn(`⚠️ [F1] Could not fetch PR for description update: HTTP ${prRes.status}`);
      return;
    }
    const prData = (await prRes.json()) as { body?: string | null };
    const originalBody = prData.body || '';

    const lowerReview = reviewText.toLowerCase();
    const hasCritical =
      lowerReview.includes('critical') ||
      lowerReview.includes('security') ||
      lowerReview.includes('vulnerability') ||
      lowerReview.includes('injection') ||
      lowerReview.includes('xss');
    const hasMedium =
      lowerReview.includes('performance') ||
      lowerReview.includes('memory') ||
      lowerReview.includes('leak') ||
      lowerReview.includes('warning');
    const riskBadge = hasCritical
      ? '🔴 **Risk Level: HIGH** — Critical issues require attention before merge.'
      : hasMedium
        ? '🟡 **Risk Level: MEDIUM** — Performance or style improvements suggested.'
        : '🟢 **Risk Level: LOW** — Changes look clean and safe to merge.';

    const DESCRIPTION_TAG = '<!-- reviewground-pr-description -->';
    const aiSection = `\n\n---\n\n### 🤖 ReviewGround AI Summary\n\n${riskBadge}\n\n> *Auto-generated by [ReviewGround](https://github.com/arungupta1526/reviewground). Remove this section if not needed.*\n\n${DESCRIPTION_TAG}`;

    let newBody: string;
    if (originalBody.includes(DESCRIPTION_TAG)) {
      newBody = originalBody.replace(
        /\n\n---\n\n### 🤖 ReviewGround AI Summary[\s\S]*?<!-- reviewground-pr-description -->/,
        aiSection
      );
    } else {
      newBody = originalBody + aiSection;
    }

    const updateRes = await fetch(`https://api.github.com/repos/${repo}/pulls/${prNumber}`, {
      method: 'PATCH',
      headers,
      body: JSON.stringify({ body: newBody }),
    });

    if (updateRes.ok) {
      console.log(`✅ [F1] Updated PR #${prNumber} description with AI summary and risk badge.`);
    } else {
      console.warn(`⚠️ [F1] Could not update PR description: HTTP ${updateRes.status}`);
    }
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    console.warn(`⚠️ [F1] Error updating PR description: ${msg}`);
  }
}

/**
 * Creates a GitHub Check Run that acts as a pass/fail gate for branch protection.
 */
export async function createCheckRun(
  reviewText: string,
  token: string,
  repo: string,
  prNumber: string
): Promise<void> {
  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'User-Agent': 'ReviewGround-CI-Reviewer',
    'Content-Type': 'application/json',
  };

  try {
    const prRes = await fetch(`https://api.github.com/repos/${repo}/pulls/${prNumber}`, { headers });
    if (!prRes.ok) {
      console.warn(`⚠️ [F3] Could not fetch PR SHA for check run: HTTP ${prRes.status}`);
      return;
    }
    const prData = (await prRes.json()) as { head?: { sha?: string } };
    const headSha = prData.head?.sha;
    if (!headSha) {
      console.warn('⚠️ [F3] No HEAD SHA found on PR. Skipping check run creation.');
      return;
    }

    const lowerReview = reviewText.toLowerCase();
    const isClean =
      lowerReview.includes('all changes look clean') ||
      lowerReview.includes('looks clean') ||
      lowerReview.includes('looks solid');

    const hasCriticalIssues =
      !isClean &&
      (lowerReview.includes('critical bug') ||
        lowerReview.includes('critical vulnerability') ||
        lowerReview.includes('critical issue') ||
        lowerReview.includes('critical regression') ||
        lowerReview.includes('❌') ||
        lowerReview.includes('secret leak detected') ||
        lowerReview.includes('sql injection') ||
        lowerReview.includes('security vulnerability detected'));

    const conclusion = hasCriticalIssues ? 'failure' : 'success';
    const title = hasCriticalIssues
      ? 'ReviewGround: Critical issues found — review required'
      : 'ReviewGround: Code review passed';
    const summary = hasCriticalIssues
      ? 'ReviewGround detected critical security or correctness issues in this PR. Please address them before merging.'
      : 'ReviewGround AI review completed. No critical issues were found in this PR.';

    const checkRes = await fetch(`https://api.github.com/repos/${repo}/check-runs`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        name: 'ReviewGround AI Review',
        head_sha: headSha,
        status: 'completed',
        conclusion,
        output: {
          title,
          summary,
          text: reviewText.slice(0, 65535),
        },
      }),
    });

    if (checkRes.ok) {
      console.log(`✅ [F3] GitHub Check Run created (conclusion: ${conclusion}) for PR #${prNumber}.`);
    } else {
      const errText = await checkRes.text();
      console.warn(`⚠️ [F3] Could not create Check Run: HTTP ${checkRes.status} — ${errText.slice(0, 200)}`);
      console.warn('ℹ️  Ensure the workflow has `checks: write` permission for GitHub Check Run gate.');
    }
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    console.warn(`⚠️ [F3] Error creating Check Run: ${msg}`);
  }
}
