/**
 * ReviewGround - Automated PR Description & Walkthrough Generator
 * Feature 2: Inspects git diffs to automatically generate a structured PR Summary,
 * Key Changes bullets, Walkthrough Table, Testing Checklist, and Risk Badge.
 * Injects cleanly into GitHub PR description without overwriting human author notes.
 */

import * as fs from 'fs';
import { getPullRequestDiff } from './reviewer.js';
import { ProviderManager, ReviewOptions } from './providers/index.js';

export const PR_DESCRIPTION_TAG = '<!-- reviewground-pr-description -->';

export interface PrDescribeConfig {
  githubToken?: string;
  repo?: string;
  prNumber?: string;
  baseBranch?: string;
  provider?: string;
  model?: string;
  fallbackModels?: string[];
  temperature?: number;
  maxTokens?: number;
  geminiApiKey?: string;
  openaiApiKey?: string;
  anthropicApiKey?: string;
  groqApiKey?: string;
  deepseekApiKey?: string;
  openrouterApiKey?: string;
  llmBaseUrl?: string;
  llmApiKey?: string;
  enableSearchGrounding?: boolean;
}

/**
 * Builds the prompt instructed to output an executive summary, key changes,
 * a walkthrough table (| File | Summary |), a testing checklist, and risk assessment.
 */
export function buildDescribePrompt(diff: string): string {
  return `You are a Principal Software Engineer creating a comprehensive Pull Request Description.

Analyze the following Git diff and generate a clean, professional Pull Request Description.

Strictly adhere to this Markdown structure:

### 📝 Summary of Changes
A concise 2-3 sentence overview explaining what problem this PR solves and what was implemented.

### 🔑 Key Changes
- Bullet points detailing the key architecture, logic, or schema modifications.

### 🔍 Changes Walkthrough
| File | Summary of Changes |
|---|---|
(Generate a table row for each modified file in the diff with a 1-sentence summary of what changed in that file)

### 🧪 Testing Checklist
- [ ] Unit tests added / updated
- [ ] Manual verification completed
- [ ] No regressions in core workflows

### 🛡️ Risk Assessment
- 🟢 **Risk Level: LOW** (or 🟡 **Risk Level: MEDIUM** or 🔴 **Risk Level: HIGH**) — 1-sentence explanation of risk impact.

Git Diff:
\`\`\`diff
${diff.slice(0, 28000)}
\`\`\`
`;
}

/**
 * Merges AI-generated walkthrough markdown with the original PR body:
 * 1. If original body is empty or whitespace: uses AI generated content directly.
 * 2. If original body already contains PR_DESCRIPTION_TAG: replaces only that section.
 * 3. If original body has author text: preserves author text and appends AI section below.
 */
export function mergePrDescriptionBody(originalBody: string, aiGeneratedMarkdown: string): string {
  const trimmed = originalBody.trim();
  const aiSection = `\n\n---\n\n### 🤖 ReviewGround PR Description & Walkthrough\n\n${aiGeneratedMarkdown.trim()}\n\n> *Auto-generated by [ReviewGround](https://github.com/arungupta1526/ReviewGround). Edit as needed.*\n\n${PR_DESCRIPTION_TAG}`;

  // If empty or only comments
  if (!trimmed || /^(<!--[\s\S]*?-->\s*)+$/.test(trimmed)) {
    return `${aiGeneratedMarkdown.trim()}\n\n---\n> *Auto-generated by [ReviewGround](https://github.com/arungupta1526/ReviewGround).*\n\n${PR_DESCRIPTION_TAG}`;
  }

  // If previous ReviewGround section already exists, replace it
  if (originalBody.includes(PR_DESCRIPTION_TAG)) {
    const regex = /\n\n---\n\n### 🤖 ReviewGround PR Description & Walkthrough[\s\S]*?<!-- reviewground-pr-description -->/;
    if (regex.test(originalBody)) {
      return originalBody.replace(regex, aiSection);
    }
    // Fallback if header was modified but tag remains
    const tagIndex = originalBody.indexOf(PR_DESCRIPTION_TAG);
    return originalBody.slice(0, tagIndex).trimEnd() + aiSection;
  }

  // Otherwise, append below author's original text
  return originalBody + aiSection;
}

/**
 * Updates the pull request description via GitHub API.
 */
export async function updatePrBodyOnGitHub(
  newBody: string,
  token: string,
  repo: string,
  prNumber: string
): Promise<boolean> {
  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'User-Agent': 'ReviewGround-PR-Describer',
    'Content-Type': 'application/json',
  };

  try {
    const res = await fetch(`https://api.github.com/repos/${repo}/pulls/${prNumber}`, {
      method: 'PATCH',
      headers,
      body: JSON.stringify({ body: newBody }),
      signal: AbortSignal.timeout(15000),
    });

    if (res.ok) {
      console.log(`✅ [Describe] Successfully updated PR #${prNumber} description with Walkthrough.`);
      return true;
    }
    const errText = await res.text();
    console.warn(`⚠️ [Describe] Could not update PR body (HTTP ${res.status}): ${errText.slice(0, 200)}`);
    return false;
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    console.warn(`⚠️ [Describe] Network error updating PR body: ${msg}`);
    return false;
  }
}

/**
 * Fetches the current PR description from GitHub API.
 */
export async function fetchCurrentPrBody(
  token: string,
  repo: string,
  prNumber: string
): Promise<string> {
  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'User-Agent': 'ReviewGround-PR-Describer',
  };

  try {
    const res = await fetch(`https://api.github.com/repos/${repo}/pulls/${prNumber}`, {
      headers,
      signal: AbortSignal.timeout(10000),
    });
    if (!res.ok) return '';
    const data = (await res.json()) as { body?: string | null };
    return data.body || '';
  } catch {
    return '';
  }
}

/**
 * Main execution function for Feature 2: Automated PR Description & Walkthrough Generator.
 */
export async function runPrDescribe(config: PrDescribeConfig): Promise<string | null> {
  const token = (config.githubToken || process.env.GITHUB_TOKEN || '').trim();
  const repo = (config.repo || process.env.REPO_FULL_NAME || process.env.GITHUB_REPOSITORY || '').trim();
  const prNumber = (config.prNumber || process.env.PR_NUMBER || '').trim();

  if (!token || !repo || !prNumber) {
    console.warn('⚠️ [Describe] Missing GITHUB_TOKEN, REPO, or PR_NUMBER. Skipping PR description generation.');
    return null;
  }

  // 1. Fetch PR Diff
  const diff = await getPullRequestDiff(repo, prNumber, token, config.baseBranch || 'main');
  if (!diff || diff.trim().length === 0) {
    console.log('ℹ️ [Describe] No changes found in PR diff. Skipping description generation.');
    return null;
  }

  // 2. Initialize Provider Manager
  const providerManager = new ProviderManager({
    preferredProvider: config.provider,
    geminiApiKey: config.geminiApiKey,
    openaiApiKey: config.openaiApiKey,
    anthropicApiKey: config.anthropicApiKey,
    groqApiKey: config.groqApiKey,
    deepseekApiKey: config.deepseekApiKey,
    openrouterApiKey: config.openrouterApiKey,
    llmBaseUrl: config.llmBaseUrl,
    llmApiKey: config.llmApiKey,
  });

  const configuredProviders = providerManager.getConfiguredProviders();
  if (configuredProviders.length === 0) {
    console.warn('⚠️ [Describe] No AI provider keys configured. Skipping PR description generation.');
    return null;
  }

  const prompt = buildDescribePrompt(diff);
  const options: ReviewOptions = {
    model: config.model,
    fallbackModels: config.fallbackModels,
    temperature: config.temperature ?? 0.2,
    maxTokens: config.maxTokens ?? 2048,
    enableSearchGrounding: config.enableSearchGrounding !== false,
  };

  console.log(`🤖 [Describe] Generating PR description & walkthrough via ${providerManager.getConfiguredProviders()[0]?.name}...`);
  const response = await providerManager.executeReview(prompt, options);
  if (!response || !response.text.trim()) {
    console.warn('⚠️ [Describe] AI provider returned empty response for PR description.');
    return null;
  }

  const generatedMarkdown = response.text.trim();

  // 3. Fetch existing PR body and merge
  const currentBody = await fetchCurrentPrBody(token, repo, prNumber);
  const updatedBody = mergePrDescriptionBody(currentBody, generatedMarkdown);

  // 4. Update PR description on GitHub
  await updatePrBodyOnGitHub(updatedBody, token, repo, prNumber);

  // 5. Append to Step Summary if available
  const stepSummaryFile = process.env.GITHUB_STEP_SUMMARY;
  if (stepSummaryFile && fs.existsSync(stepSummaryFile)) {
    const summaryCard = `### 📝 ReviewGround Generated PR Description\n\n${generatedMarkdown}\n`;
    await fs.promises.appendFile(stepSummaryFile, summaryCard);
  }

  return generatedMarkdown;
}
